image:
 - Visual Studio 2017
 - Visual Studio 2019

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  matrix:
    - SHARED_LIB: OFF

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - vcpkg install tl-expected catch2 nlohmann-json fmt --triplet x64-windows
  - vcpkg integrate install
  - cd %APPVEYOR_BUILD_FOLDER%

before_build:
 - git submodule init
 - git submodule update
 - mkdir _build
 - cmake
  -B _build
  -A x64
  -Dskyr_WARNINGS_AS_ERRORS=OFF
  -Dskyr_BUILD_TESTS=ON
  -Dskyr_BUILD_DOCS=OFF
  -Dskyr_BUILD_EXAMPLES=OFF
  -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake
  -DBUILD_SHARED_LIBS=%SHARED_LIB%
  .

build_script:
  - cmake --build _build

test_script:
  - cmake --build _build --target RUN_TESTS
  - cmake --build _build --target install


cache: c:\Tools\vcpkg\installed\

matrix:
  fast_finish: true

on_failure:
 - type _build\Testing\Temporary\LastTest.log
